stages:
- test
- coverage

image: python:3.6

before_script:
- pip install tox

flake8:
  script: tox -e flake8

isort:
  script: tox -e isort

pydocstyle:
  script: tox -e pydocstyle

black:
  script: tox -e black

python2.7:
  image: python:2.7
  script: tox -e py27
  artifacts:
    paths:
    - .coverage.*
    expire_in: 1 hour

python3.4:
  image: python:3.4
  script: tox -e py34
  artifacts:
    paths:
    - .coverage.*
    expire_in: 1 hour

python3.5:
  image: python:3.5
  script: tox -e py35
  artifacts:
    paths:
    - .coverage.*
    expire_in: 1 hour

python3.6:
  image: python:3.6
  script: tox -e py36
  artifacts:
    paths:
    - .coverage.*
    expire_in: 1 hour

manifest:
  script: tox -e manifest

metadata:
  script: tox -e metadata

doc8:
  script: tox -e doc8
{%- if cookiecutter.project_doc == 'sphinx' %}

sphinx:
  script: tox -e sphinx
{%- endif %}

coverage:
  stage: coverage
  script: tox -e coverage
  dependencies:
  - python2.7
  - python3.4
  - python3.5
  - python3.6
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
